# Generated by Django 5.0.4 on 2024-05-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bank',
            new_name='bank_id',
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_name',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
