# Generated by Django 5.0.4 on 2024-05-03 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_bank_branch_bank_id_branch_bank_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bank_id',
            new_name='bank',
        ),
    ]
